name: Tests

on:
  push:
    branches: [main, develop, feature/*, bugfix/*, refactor/*, issue/*, devops/*]
  pull_request:
    branches: [main, develop, feature/*, bugfix/*, refactor/*, issue/*, devops/*]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install unittest-xml-reporting

      - name: Install optional dependencies
        run: |
          pip install -e ".[scrubbing]"
        continue-on-error: true

      - name: Run tests with xunit output
        run: |
          python test_runner.py --xunit-file=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: test-results.xml

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results.xml
          check_name: "Test Results (Python ${{ matrix.python-version }})"
